---
- name: Execute management node playbooks
  hosts: management
  gather_facts: true

  tasks:

    - name: Step 1 - Host file configuration
      import_tasks: step1.yml

    - name: Step 2 -  Hostname file configuration
      import_tasks: step2.yml

    - name: Step 3 - Edit /etc/resolv.conf
      import_tasks: step3.yml

    - name: Step 4 - Setup network interface
      import_tasks: step4.yml

    - name: Step 5 - Create second partition
      import_tasks: step5.yml

    - name: Step 6 - Download packages
      import_tasks: step6.yml

    - name: Step 7 - Setup /tftpboot and syslinux
      import_tasks: step7.yml

    - name: Step 8 - Mount alma linux
      import_tasks: step8.yml

    - name: Step 9 - Fix Alma8 permissions
      import_tasks: step9.yml

    - name: Step 10 - Start and enable httpd
      import_tasks: step10.yml

    - name: Step 11 - Setup dhcpd.conf
      import_tasks: step11.yml

    - name: Step 12 - Enable and start xinetd
      import_tasks: step12.yml

    - name: Step 13 - Turn off firewall and disable
      import_tasks: step13.yml

    - name: Step 14 - Setup kickstart file
      import_tasks: step14.yml

    - name: Step 15 - Fix selinux permissions
      import_tasks: step15.yml

    - name: Step 16 - Setup powerman
      import_tasks: step16.yml

    - name: Step 17 - Setup conman
      import_tasks: step17.yml

    - name: Step 18 - Create ssh key for root user
      import_tasks: step18.yml

