---
- name: Fix selinux permissions and restart
  hosts: management
  become: yes

  tasks:
    - name: Restore SELinux context for /var/www/html/alma8-install/
      command: restorecon -Rv /var/www/html/alma8-install/

    - name: Set SELinux context for /var/www/html/alma8-install/
      command: chcon -R -t httpd_sys_content_t /var/www/html/alma8-install/

    - name: Restore SELinux context for /tftpboot
      command: restorecon -Rv /tftpboot

    - name: Set SELinux context for /tftpboot
      command: chcon -R -t public_content_t /tftpboot

    - name: Restart TFTP service
      systemd:
        name: tftp
        state: restarted

    - name: Restart xinetd service
      systemd:
        name: xinetd
        state: restarted

    - name: Restart Apache HTTP server
      systemd:
        name: httpd
        state: restarted

