---

- name: Use template file to write to /etc/hosts
  hosts: management
  vars_files: step1_vars.yml
  tasks: 

    - name: Write main node to file.
      blockinfile:
        path: /etc/hosts
        block: |
          {{ ext_net }}

    - name: Run Template file
      lineinfile:
        dest: /etc/hosts
        line: "{{ lookup('template', './step1_write.j2') }}"
        insertafter: EOF
      become: true
