---
- name: Edit /etc/resolv.conf
  hosts: management
  become: yes
  
  tasks:
    - name: Backup current resolv.conf file
      become: yes
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.bak
        backup: yes
        remote_src: yes

    - name: Add lines to resolv.conf
      become: yes
      blockinfile:
        path: /etc/resolv.conf
        state: present
        block: |
          domain llnl.gov
          nameserver 192.12.17.17
