---
 - name: Step 12 - Enable and Start Xinetd & Create /etc/xinetd.d/tftp file
   hosts: management
   remote_user: root

   tasks: 
     - name: Modify xinetd.d/tftp
       template:
         src: "./xinetd-tftp.j2"
         dest: "/etc/xinetd.d/tftp"
     - name: Start and enable xinetd
       ansible.builtin.systemd:
         name: xinetd
         state: started
         enabled: true

