---
- name: Enable and Start httpd
  hosts: management
  tasks:
    - name: Unmount USB or ISO
      command: umount /mnt/alma8-install/
    - name: Proceed with systemctl
      command: systemctl enable --now httpd
