---
- name: Step Two 
  hosts: management
  become: yes
  vars_files:
    - mgmt_vars.yml

  tasks:
  - name: write management node hostname in /etc/hostname
    ansible.builtin.lineinfile:
      path: /etc/hostname 
      line: "{{ cluster }}1"
