---

- name: Use template file to write to /etc/hosts
  hosts: management
  gather_facts: true
  vars_files:
    -  mgmt_vars.yml

  tasks: 

    - name: Write main node to file.
      blockinfile:
        path: /etc/hosts
        block: |
          {{ ext_net }}
          {{ lookup('template', './step1_write.j2') }}

#    - name: Run Template file
#      blockinfile:
#        path: /etc/hosts
#        block: | 
#          {{ lookup('template', './step1_write.j2') }}
#        insertafter: EOF
#      become: true
