---
- name: Do updates on nodes 
  hosts: compute
  
  tasks:
    - name: Disable epel
      dnf:
        disablerepo: epel 

    - name: Run security updates
      dnf:
        name: '*'
        state: latest
        security: yes

    - name: Import the public key for EL repo
      command: rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

    - name: Install EL Repo
      dnf:
        name: https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
        state: present

    - name: Do general upgrades
      dnf:
        name: '*'
        state: latest

    - name: Clear out cache part 1
      command: dnf clean all

    - name: Clear out cache part 2
      dnf:
        name: '*'
        state: latest
        nobest: true

    - name: Reboot the node
      reboot:
        test_command: echo $hostname

    - name: Enable epel
      dnf:
        enablerepo: epel
      

